import { BrowserWindow } from "electron";
import accountController from "./AccountController";
import BillController from "./BillController";
import machineController from "./MachineController";
import ProductController from "./ProductController";
accountController.init();
machineController.init();
ProductController.init();
BillController.init();
export {};
